apiVersion: v1
kind: ConfigMap
metadata:
  name: kubeconfig-in-cluster
  namespace: {{ .Release.Namespace }}
  labels:
    k8s-app: {{ .Release.Name }}
    tier: node
data:
  kubeconfig: |
    apiVersion: v1
    kind: Config
    clusters:
    - cluster:
        server: https://kubernetes.default.svc
        certificate-authority: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      name: default-cluster
    contexts:
    - context:
        cluster: default-cluster
        namespace: default
        user: default-auth
      name: default-context
    current-context: default-context
    users:
    - name: default-auth
      user:
        tokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token

