{{- if semverCompare ">= 1.9-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: apps/v1
{{- else if semverCompare ">= 1.8-0, <= 1.9-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: apps/v1beta2
{{- else -}}
apiVersion: apps/v1beta1
{{- end }}
kind: Deployment
metadata:
  name: {{ template "dex-k8s-authenticator.name" . }}
  labels:
    app: {{ template "dex-k8s-authenticator.name" . }}
    env: {{ default "dev" .Values.global.deployEnv }}
    chart: {{ template "dex-k8s-authenticator.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "dex-k8s-authenticator.name" . }}
      env: {{ default "dev" .Values.global.deployEnv }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "dex-k8s-authenticator.name" . }}
        env: {{ default "dev" .Values.global.deployEnv }}
        release: {{ .Release.Name }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args: [ "--config", "config.yaml" ]
        ports:
        - name: http
          containerPort: {{ default "5555" .Values.dexK8sAuthenticator.port }}
          protocol: TCP
        {{- if and .Values.livenessProbe (not .Values.livenessProbe.disabled) }}
        livenessProbe:
          {{- if .Values.livenessProbe.tcpSocket }}
          tcpSocket:
            port: http
          {{- else }}
          httpGet:
            path: {{ template "dex-k8s-authenticator.healthCheckPath" . }}
            port: http
          {{- end }}
          {{- $probe := .Values.livenessProbe }}
          {{- if $probe.initialDelaySeconds }}
          initialDelaySeconds: {{ $probe.initialDelaySeconds }}
          {{- end }}
          {{- if $probe.periodSeconds }}
          periodSeconds: {{ $probe.periodSeconds }}
          {{- end }}
          {{- if $probe.timeoutSeconds }}
          timeoutSeconds: {{ $probe.timeoutSeconds }}
          {{- end }}
          {{- if $probe.successThreshold }}
          successThreshold: {{ $probe.successThreshold }}
          {{- end }}
          {{- if $probe.failureThreshold }}
          failureThreshold: {{ $probe.failureThreshold }}
          {{- end }}
        {{- else if not (and .Values.livenessProbe .Values.livenessProbe.disabled) }}
        livenessProbe:
          httpGet:
            path: {{ template "dex-k8s-authenticator.healthCheckPath" . }}
            port: http
        {{- end }}
        {{- if .Values.readinessProbe }}
        readinessProbe:
          {{- if .Values.readinessProbe.tcpSocket }}
          tcpSocket:
            port: http
          {{- else }}
          httpGet:
            path: {{ template "dex-k8s-authenticator.healthCheckPath" . }}
            port: http
          {{- end }}
          {{- $probe := .Values.readinessProbe }}
          {{- if $probe.initialDelaySeconds }}
          initialDelaySeconds: {{ $probe.initialDelaySeconds }}
          {{- end }}
          {{- if $probe.periodSeconds }}
          periodSeconds: {{ $probe.periodSeconds }}
          {{- end }}
          {{- if $probe.timeoutSeconds }}
          timeoutSeconds: {{ $probe.timeoutSeconds }}
          {{- end }}
          {{- if $probe.successThreshold }}
          successThreshold: {{ $probe.successThreshold }}
          {{- end }}
          {{- if $probe.failureThreshold }}
          failureThreshold: {{ $probe.failureThreshold }}
          {{- end }}
        {{- else }}
        readinessProbe:
          httpGet:
            path: {{ template "dex-k8s-authenticator.healthCheckPath" . }}
            port: http
        {{- end }}
        env:
          {{- with .Values.podEnv }}
          {{- toYaml . | nindent 12 }}
          {{- end }}
        volumeMounts:
        - name: config
          subPath: config.yaml
          mountPath: /app/config.yaml
        - name: capem
          mountPath: /etc/ca.crt
{{- if .Values.caCerts.enabled }}
{{- range .Values.caCerts.secrets }}
        - name: {{ template "dex-k8s-authenticator.fullname" $ }}-{{ .name }}
          subPath: {{ .name }}
          mountPath: /certs/{{ .filename }}
{{- end }}
{{- end }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}
      {{- end }}
      volumes:
      - name: config
        configMap:
          name: {{ template "dex-k8s-authenticator.fullname" . }}
      - name: capem
        hostPath:
          path: /etc/kubernetes/pki/ca.crt
          type: FileOrCreate
{{- if .Values.caCerts.enabled }}
{{- range .Values.caCerts.secrets }}
      - name: {{ template "dex-k8s-authenticator.fullname" $ }}-{{ .name }}
        secret:
          secretName: {{ template "dex-k8s-authenticator.fullname" $ }}-{{ .name }}
{{- end }}
{{- end }}
