---
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: {{ .Release.Namespace }}
data:
  {{- range $key, $value := .Values.DNSConfig }}
  {{ $key }}: |-
    {{- tpl $value $ | nindent 4 }}
  {{- end }}